services:
  db:
    image: mongo:7.0.2
    container_name: cms-db
    env_file:
      - .env
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - hz-data:/data/db
      - ./ci/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  hz-data:
