name: deployment

on:
  push:
    branches:
      - main
      - dev
      - staging
    paths-ignore:
      - "dump/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/ab7z/cms:${{ github.ref_name }}
          platforms: linux/arm64/v8
          cache-from: type=registry,ref=ghcr.io/ab7z/cms:buildcache
          cache-to: type=inline,ref=ghcr.io/ab7z/cms:buildcache,mode=max

  deployment:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: copy deployment tar
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HZ_HOST }}
          username: ${{ secrets.HZ_SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          overwrite: true
          source: "ci"
          target: "/root/"
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        env:
          USERNAME: ab7z
          ACTOR: ab7z
          REF_NAME: ${{ github.ref_name }}
          TOKEN: ${{ secrets.GH_TOKEN }}
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          MONGO_INITDB_DATABASE: ${{ secrets.MONGO_INITDB_DATABASE }}
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
          MONGO_DB_USER: ${{ secrets.MONGO_DB_USER }}
          MONGO_DB_PASS: ${{ secrets.MONGO_DB_PASS }}
          MAIN_TRIGGER: ${{ vars.NETLIFY_MAIN_TRIGGER }}
          DEV_TRIGGER: ${{ vars.NETLIFY_DEV_TRIGGER }}
          STAGING_TRIGGER: ${{ vars.NETLIFY_STAGING_TRIGGER }}
        with:
          host: ${{ secrets.HZ_HOST }}
          username: ${{ secrets.HZ_SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          envs: >
            TOKEN,
            REF_NAME,
            USERNAME,
            ACTOR,
            PAYLOAD_SECRET,
            MONGO_DB_NAME,
            MONGO_INITDB_DATABASE,
            MONGO_INITDB_ROOT_USERNAME,
            MONGO_INITDB_ROOT_PASSWORD,
            MONGO_DB_USER,
            MONGO_DB_PASS,
            MAIN_TRIGGER,
            DEV_TRIGGER,
            STAGING_TRIGGER
          script: bash ./ci/deployment.sh
