name: only publish

on:
  push:
    branches:
      - main
      - dev
      - staging
    paths:
      - "dump/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: webhook netlify
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            curl -X POST -d '{}' ${{ vars.NETLIFY_MAIN_TRIGGER }}
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            curl -X POST -d '{}' ${{ vars.NETLIFY_DEV_TRIGGER }}
          else
            curl -X POST -d '{}' ${{ vars.NETLIFY_STAGING_TRIGGER }}
          fi
